import * as path from "path";
import { SessionMetadata, SessionMessage } from "./parser";

const PKG_VERSION: string = (() => {
  try {
    return require(path.join(__dirname, "..", "package.json")).version ?? "0.0.0";
  } catch {
    return "0.0.0";
  }
})();

export function generateSummary(
  metadata: SessionMetadata,
  messages: SessionMessage[],
  maxPreview: number = 500
): string {
  const lines: string[] = [];

  const slug = metadata.slug ?? "unknown-session";
  let dateStr = "unknown";
  if (metadata.startTime) {
    try {
      const dt = new Date(metadata.startTime);
      dateStr = dt.toISOString().replace("T", " ").replace(/\.\d+Z$/, " UTC");
    } catch {
      dateStr = metadata.startTime;
    }
  }

  lines.push(`# Session: ${slug}`);
  lines.push("");
  lines.push(`**Session ID:** \`${metadata.sessionId}\``);
  lines.push(`**Datum:** ${dateStr}`);
  lines.push(`**Projekt:** \`${metadata.cwd ?? "?"}\``);
  lines.push(`**Branch:** ${metadata.gitBranch ?? "?"}`);
  lines.push(`**Claude Code:** v${metadata.version ?? "?"}`);
  lines.push(`**Turns:** ${metadata.totalTurns}`);
  lines.push("");
// --- NEU: System Status rendern ---
  if (metadata.projectContext) {
    lines.push("## System Status & Projekt-Gedächtnis");
    lines.push("");
    
    if (metadata.projectContext.settingsBloatWarning) {
      lines.push(`> ${metadata.projectContext.settingsBloatWarning}`);
    }
    if (metadata.projectContext.settingsError) {
      lines.push(`> ${metadata.projectContext.settingsError}`);
    }
    if (metadata.projectContext.bypassPermissions !== undefined) {
      lines.push(`- **YOLO-Modus (Bypass):** \`${metadata.projectContext.bypassPermissions}\``);
    }

    if (metadata.projectContext.memoryMd) {
      lines.push("\n### Aktives Claude-Gedächtnis (MEMORY.md)");
      lines.push("```markdown");
      lines.push(metadata.projectContext.memoryMd);
      lines.push("```");
    }
    lines.push("");
  }
  // --- ENDE NEU ---
  if (metadata.toolUses.length > 0) {
    const toolCounts: Record<string, number> = {};
    for (const t of metadata.toolUses) {
      toolCounts[t] = (toolCounts[t] ?? 0) + 1;
    }
    const sorted = Object.entries(toolCounts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 15);

    lines.push("## Tool Usage");
    lines.push("");
    for (const [tool, count] of sorted) {
      lines.push(`- ${tool}: ${count}x`);
    }
    lines.push("");
  }

  lines.push("## Conversation Flow");
  lines.push("");
  const userMsgs = messages.filter((m) => m.role === "user");
  const displayMsgs = userMsgs.slice(0, 50);

  for (let i = 0; i < displayMsgs.length; i++) {
    let preview = displayMsgs[i].content.slice(0, 200).replace(/\n/g, " ");
    if (displayMsgs[i].content.length > 200) {
      preview += "...";
    }
    lines.push(`${i + 1}. **User:** ${preview}`);
  }

  if (userMsgs.length > 50) {
    lines.push("");
    lines.push(`*... and ${userMsgs.length - 50} more messages*`);
  }
  lines.push("");

  const assistantMsgs = messages.filter((m) => m.role === "assistant");
  if (assistantMsgs.length > 0) {
    lines.push("## First Response (excerpt)");
    lines.push("");
    let first = assistantMsgs[0].content.slice(0, maxPreview);
    if (assistantMsgs[0].content.length > maxPreview) {
      first += "\n\n*[...truncated]*";
    }
    lines.push(first);
    lines.push("");

    if (assistantMsgs.length > 1) {
      lines.push("## Last Response (excerpt)");
      lines.push("");
      let last = assistantMsgs[assistantMsgs.length - 1].content.slice(0, maxPreview);
      if (assistantMsgs[assistantMsgs.length - 1].content.length > maxPreview) {
        last += "\n\n*[...truncated]*";
      }
      lines.push(last);
      lines.push("");
    }
  }

  const now = new Date();
  const dateFormatted = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")} ${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}`;

  lines.push("---");
  lines.push(`*Generated by Schroedinger Sync v${PKG_VERSION} | ${dateFormatted}*`);

  return lines.join("\n");
}
